# Generated by Django 3.2.10 on 2021-12-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('type', models.PositiveIntegerField(default=0)),
                ('covered', models.BooleanField(default=True)),
                ('flag', models.BooleanField(default=False)),
                ('tempUncovered', models.BooleanField(default=False)),
            ],
        ),
    ]
